version: 2
jobs:
  build_project:
    docker:
      - image: haskell:8.4.3
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-work-{{ checksum "stack.yaml" }}-{{ checksum "my-project.cabal" }}
      - run: stack setup
      - run: stack build
      - run: stack test
      - save-cache:
          key: stack-work-{{ checksum "stack.yaml" }}-{{ checksum "my-project.cabal" }}
          paths:
            - ".stack-work"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project